image: node:12.19.0-alpine

stages:
  - build
  - test
  - deploy
build:
  stage: build
  only:
    - master
  script:
    - npm install  --progress=false
    - npm run build
  artifacts:
    paths:
      - build/
test:
  stage: test
  script:
    - npm test
deploy:
  stage: deploy
  only:
    - master
  image: tstrohmeier/awscli
  script:
    - aws s3 cp build/ s3://react-cicd-test/ --recursive
  when: manual
